// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl6hw4VNsw8zptObJEtYl7OGAFVqsTdPU',
    appId: '1:63006088249:web:eb76abb5282af3d35501e8',
    messagingSenderId: '63006088249',
    projectId: 'blackclap-b30ab',
    authDomain: 'blackclap-b30ab.firebaseapp.com',
    storageBucket: 'blackclap-b30ab.firebasestorage.app',
    measurementId: 'G-BEER5P0XMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3bDd4kQVESCP0_6gZ1hg-wekxs_C4pvs',
    appId: '1:63006088249:android:306957e50fb97e515501e8',
    messagingSenderId: '63006088249',
    projectId: 'blackclap-b30ab',
    storageBucket: 'blackclap-b30ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0xpKi6Um7zRS67Wdnd9ZYPUTu4NiCfmA',
    appId: '1:63006088249:ios:fef3746837d429cf5501e8',
    messagingSenderId: '63006088249',
    projectId: 'blackclap-b30ab',
    storageBucket: 'blackclap-b30ab.firebasestorage.app',
    iosBundleId: 'com.example.yoursBird',
  );

}